### ISSUE TITLE
Error Недостаточно ресурсов памяти для обработки этой команды.

### ISSUE THREAD

**Issue by mrerro** [profcomff/print-winapp#53]
Есть подозрения на утечку памяти либо в системе, либо в используемой библиотеки [QRCoder](https://github.com/codebude/QRCoder). Мысли попробовать сменить генератор кодов. А так же отделить генерацию чтобы она не отражалась на сокете.

**Comment by mrerro** [comment]
По статистики ОЗУ нельзя судить, что то то течет. Проблема с мая не проявлялась повторно. Возможно она пропала по причине обновлений Винды или из за рефакторного выведения создания qr кода из обработке команд сокета.

**Comment by grigoriev-semyon** [comment]
Тогда пока что оставим, если за сентябрь не повторится то можно закрывать

**Comment by mrerro** [comment]
Отмена. Проблема переехала и это не зависит от оперативки. Замечена проблема библиотеки генерации QR по прошествии ~12 дней.  `print terminal qr generator exception`

> System.ComponentModel.Win32Exception (8): Недостаточно ресурсов памяти для обработки этой команды.
   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)   at System.Windows.Threading.Dispatcher..ctor()
   at System.Windows.Threading.Dispatcher.get_CurrentDispatcher()
   at QRCoder.Xaml.XamlQRCode.GetGraphic(Int32 pixelsPerModule, String darkColorHex, String lightColorHex, Boolean drawQuietZones)
   at PrinterApp.PrinterModel.GenerateQr(String value)

**Comment by mrerro** [comment]
### Выкатил смену библиотеки Qr. 
Посмотрим как будет вести себя.

https://github.com/profcomff/print-winapp/releases/tag/v2.1.10.0
